/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class homework9 */

#ifndef _Included_homework9
#define _Included_homework9
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     homework9
 * Method:    convert
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_homework9_convert
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
